In [91]:
import pandas as pd
import numpy as np
import torch

In [92]:
test_list = [[1, 0, 0],
                   [0, 1, 1],
                   [0, 1, 0],
                  [1, 0, 1]]

df = pd.DataFrame(test_list, columns=['var1', 'var2', 'var3'])
diagnoses = np.array(df).astype(np.uint8)
diagnoses

array([[1, 0, 0],
       [0, 1, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=uint8)

In [83]:
diagnoses = torch.tensor(diagnoses).type(torch.cuda.sparse.FloatTensor)

In [84]:
diagnoses

tensor([[1., 0., 0.],
        [0., 1., 1.],
        [0., 1., 0.],
        [1., 0., 1.]], device='cuda:0')

In [89]:
output = torch.sparse.mm(diagnoses, diagnoses.permute(1, 0))
output

tensor([[1., 0., 0., 1.],
        [0., 2., 1., 1.],
        [0., 1., 1., 0.],
        [1., 1., 0., 2.]], device='cuda:0')

In [90]:
x = torch.empty(diagnoses.shape[0], diagnoses.shape[0]).type(torch.cuda.sparse.FloatTensor)

for indx, row in df.iterrows():
    each_patient = row.values.reshape(-1, 3)
    e_p_tensor = torch.tensor(each_patient).type(torch.cuda.sparse.FloatTensor)
    each_output = torch.sparse.mm(e_p_tensor, diagnoses.permute(1, 0))
    x[indx] = each_output
    
x

tensor([[1., 0., 0., 1.],
        [0., 2., 1., 1.],
        [0., 1., 1., 0.],
        [1., 1., 0., 2.]], device='cuda:0')

In [98]:
for indx, row in df.iterrows():
    print(row.values.shape)
    each_patient = row.values.reshape(-1, diagnoses.shape[1])
    print(each_patient)

(3,)
[[1 0 0]]
(3,)
[[0 1 1]]
(3,)
[[0 1 0]]
(3,)
[[1 0 1]]
